export const API_ERROR_CODES = {
  SWAGGER_VALIDATION_ERROR: "SWAGGER_VALIDATION_ERROR",
  SWAGGER_SERIALIZATION_ERROR: "SWAGGER_SERIALIZATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ApiErrorCode = keyof typeof API_ERROR_CODES;
